### ISSUE TITLE
🗺️ Zoomify Generator: enhance output generation

### ISSUE THREAD

**Issue by bangank36** [bangank36/zoomify-generator#6]
## Summary
- The first iteration with the library works well, but in order to test all the formats, we need to improve the run.php to make it support more than 01 file in /input
- Feed the factory with an array of config contains name, output folder and its own config to be merged with the global config, that can help to try out different tileSize or different format easier

## Dev tasks

- [x] Create an array of object, starting with 01 item contain: name, output path, input path, config... and iterate over it to generate the file #7 
- [x] Create an output.json contains all info of the generated folders #8
- [x] Create an full.jpg file in the same output folder #8
- [x] Update index.html to expect the output.json and generate the lightbox on demand #9 

## Reference
N/A

**Comment by bangank36** [comment]
Closed as shipped
